### ISSUE TITLE
Does not Work with Double Commander

### ISSUE THREAD

**Issue by Neur1n** [kerol2r20/Windows-terminal-context-menu#12]
Hello, thanks for the great work. But somehow, I found that the second layer of the context menu won't show up when used with [Double Commander](https://doublecmd.sourceforge.io/).

**Comment by kerol2r20** [comment]
Sorry about that I'm not using double commander.
Does other applications setup up context menu successfully?

**Comment by Neur1n** [comment]
I also tested with [Free Commander] (https://freecommander.com/en/summary/), but it invokes the actual context menu with its own context menu (so the sub menu shown up properly) while Double Commander seems to emulate the Windows context menu.

It seems like a Double Commander issue now.
