### ISSUE TITLE
Set-ExecutionPolicy RemoteSigned Not working

### ISSUE THREAD

**Issue by Unknow-max** [kerol2r20/Windows-terminal-context-menu#13]
Hi,
First of all I would like to thank you very much for the script, it is working very well, 
very happy about that 😄.

### But there is a small issue in the readme
In the readme you say that for make the script working you need to set `executionPolicy to remoteSigned`, but with the policy like that the script will not be launched by powershell.
For make it run you must to set the policy to ` Unrestricted` with the command
`Set-ExecutionPolicy Unrestricted`

---
**And then the script will be launched correctly**

**Comment by kerol2r20** [comment]
Thank you for your report.
In fact, I have tried `Set-ExecutionPolicy RemoteSigned -scope CurrentUser` on two platform. They worked well. But I think your suggestion could work, too.
