### ISSUE TITLE
Add "Run as Admin" Items

### ISSUE THREAD

**Issue by xmha97** [kerol2r20/Windows-terminal-context-menu#15]
Hello,
Please add "Run as Admin" Items (like below image)
![Windows Explorer](https://user-images.githubusercontent.com/23485114/76995333-f79b0800-6964-11ea-941d-1136ca306228.png)
Thanks

**Comment by A-Sparowe** [comment]
This ^

**Comment by kerol2r20** [comment]
I have tried the following method.
But all of them are failed.

1. Add `HasLUAShield` for menu item
2. Executable powershell command `Start-Process wt.exe -Verb runAs`

Does anyone have any suggestion?

**Comment by xmha97** [comment]
Thanks

**Comment by Meegooo** [comment]
This works for me

`powershell -WindowStyle hidden -Command "Start-Process powershell -WindowStyle hidden -Verb RunAs -ArgumentList """"-Command C:\Users\Meegoo\AppData\Local\Microsoft\WindowsApps\wt.exe -p 'Windows PowerShell' -d '%V'"""""`
Replace path to wt with your own (or just use `wt`, it should be a proper alias) and profile with ones you want.

If anyone can find a better way to escape quotes in this monstrocity, be my guest. Took me like an hour to figure those ones out. Also, might just be me, but first "-WindowStyle hidden" seems broken. It still shows me powershell window, albeit for a slightly shorter period of time. `minimized` also works badly, it starts as usual, and only then minimizes, making it even more annoying than `hidden`


Alternatively, you can add actual administrator profiles using third party executable and just use those as normal https://github.com/microsoft/terminal/issues/1032#issuecomment-575001432

**Comment by kerol2r20** [comment]
Thank you @Meegooo 
I love gsudo solution, it's a simple way.
But gsudo is a external program, this make this script no independent.

**Comment by kerol2r20** [comment]
Hi all,

I have implemented this function.
You can give it a try 4fe75b63357566c1a0751029a51a7d1249168d43 😉

The RunAs item is closed by default, you have to turn it on at `config.json`
```
{
    "global": {
        "extended": false
    },
    "profiles": {
        "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}": {
            "showRunAs": true
        }
    }
}
```

Thanks

**Comment by felipecassiors** [comment]
For me it currently shows `Run as PowerShell`:

![image](https://user-images.githubusercontent.com/29582865/78161807-658f0700-741c-11ea-814f-7fc1a72f83f3.png)

Maybe you would like to put `PowerShell (Admin)`, so then it would look like the native Windows `Ctrl`+`X` menu:

 
![image](https://user-images.githubusercontent.com/29582865/78161959-966f3c00-741c-11ea-95c2-a2b5d051b566.png)

**Comment by kerol2r20** [comment]
Good item!
I modify the naming at a7bbd8ed75d61e4a6bb81a71f21e2d65cdc4da39

Thanks

**Comment by felipecassiors** [comment]
Awesome!

![image](https://user-images.githubusercontent.com/29582865/78165974-78a4d580-7422-11ea-9634-60178f44b214.png)
