### ISSUE TITLE
Open as Tab on a existing Terminal window

### ISSUE THREAD

**Issue by Dibbyo456** [kerol2r20/Windows-terminal-context-menu#17]
If a Terminal window already exists; open as Tab in that existing window. Don't create separate window.

**Comment by xmha97** [comment]
That's good idea 👍

**Comment by kerol2r20** [comment]
This is a pretty good idea.
In fact, I really wonder how to implement it.
But the windows terminal cannot open new tab with external command.
Ref to microsoft/terminal#607, I found there are some arguments supported, but none can do this.

Maybe this need a new feature request😀

**Comment by saadanerdetbare** [comment]
> This is a pretty good idea.
> In fact, I really wonder how to implement it.
> But the windows terminal cannot open new tab with external command.
> Ref to [microsoft/terminal#607](https://github.com/microsoft/terminal/issues/607), I found there are some arguments supported, but none can do this.
> 
> Maybe this need a new feature request😀

It seems that it does as per this pull request https://github.com/microsoft/terminal/pull/4023

**Comment by kerol2r20** [comment]
There are some information about this issue

1. https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#new-tab
2. https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md#footnote-1

**Comment by Dibbyo456** [comment]
Those arguments open new instances (Windows)
