### ISSUE TITLE
Does not work if username has a space in between

### ISSUE THREAD

**Issue by Koushikphy** [kerol2r20/Windows-terminal-context-menu#19]
The contextmenus does not work if the username has a space in between. I was having the problem. Then I fixed it by putting the path inside an inverted comma. I believe you can replace line 140 i.e this

```
$command_f = "$env:LOCALAPPDATA\Microsoft\WindowsApps\wt.exe -p `"$profileName`" -d `"%V\.`""
```

to this 

```
$command_f = "`"$env:LOCALAPPDATA\Microsoft\WindowsApps\wt.exe`" -p `"$profileName`" -d `"%V\.`""
```

**Comment by kerol2r20** [comment]
Could you create a PR for this revise?

Thanks~
