### ISSUE TITLE
Error with Google Drive

### ISSUE THREAD

**Issue by danialasghar** [kerol2r20/Windows-terminal-context-menu#5]
Latest version of Windows Terminal from Chocolatey
Windows 1909

When launching any of the profiles (cmd, ubuntu or powershell) within the google drive or any of its subfolders an error occurs: error 0x8007002

It can been:
![image](https://user-images.githubusercontent.com/46968467/75122210-6c7e6900-5669-11ea-902c-cc0a5e66e5ab.png)

**Comment by kerol2r20** [comment]
This is fixed. Please pull latest script and try again.

**Comment by danialasghar** [comment]
Seems to have fixed the google drive issue... but now the icon for Powershell only does not seem to be working. 
I removed the context entry and reinstalled even but it just shows a blank space

**Comment by kerol2r20** [comment]
It seem that  the powershell icon rule is not match your `profiles.json`.
The default rule is the commandline value equal to `powershell.exe`.

My powershell profile is like this
```json
{
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell",
        "commandline": "powershell.exe",
        "hidden": false
}
```

**Comment by danialasghar** [comment]
Yea mine matches that... it created the entry just not the icon field in the registry 
It might be because I have the -NoLogo flag set up after the powershell.exe part possibly

**Comment by kerol2r20** [comment]
It's strange. I think `-NoLogo` flag would no matter about it

**Comment by kerol2r20** [comment]
Hi @danialasghar,

I modify the matching rule.

Thank you for your suggestion.
