### ISSUE TITLE
Allow users to set extended

### ISSUE THREAD

**Issue by Kalaschnik** [kerol2r20/Windows-terminal-context-menu#6]
Thank you for this project!
I like my default shell menu to be clean. Most dev options I "hide" using the `Extended` string value in regedit.

I’ve got no clue about PowerShell logic, but maybe you can allow users to set parameters. That is for this scenario: `SetupContextMenu.ps1 --Extended`

**Comment by kerol2r20** [comment]
In fact, I have tried this. I add `Extended` in submenu, but it not work. But when I add it into main menu registry, it work well.

**Comment by Kalaschnik** [comment]
It already works for me:
![GIF 24 02 2020 13-31-36](https://user-images.githubusercontent.com/9831678/75152773-1dd4db80-570a-11ea-8a39-eeeca437a065.gif)

The corresponding registry entries:
```Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\WindowsTerminal]
"ExtendedSubCommandsKey"="Directory\\ContextMenus\\WindowsTerminal"
"Icon"="C:\\Users\\steven\\AppData\\Local\\WindowsTerminalContextIcons\\terminal.ico"
"MUIVerb"="Open Windows Terminal here"
"Extended"=""```

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\WindowsTerminal]
"ExtendedSubCommandsKey"="Directory\\ContextMenus\\WindowsTerminal"
"Icon"="C:\\Users\\steven\\AppData\\Local\\WindowsTerminalContextIcons\\terminal.ico"
"MUIVerb"="Open Windows Terminal here"
"Extended"=""```

Basically I just added the empty Extended String value in Windows Terminal Key

**Comment by kerol2r20** [comment]
Yes, I found the top level menu item can set this up. Is this what you want? I could add this function at next update 😊.
In my opinion, I want some sub-item to be `Extended`. This can also keep it clean.  
But I were not setting it successfully.

Thanks~

**Comment by Kalaschnik** [comment]
Would be cool if you could add it, and let the user choose whether or not they want to include the Extended flag before install.

**Comment by kerol2r20** [comment]
Done.
Thank you for your request.

**Comment by Kalaschnik** [comment]
Very good solution!
