### ISSUE TITLE
Check for parent reg key

### ISSUE THREAD

**Issue by skywayskase** [kerol2r20/Windows-terminal-context-menu#8]
So fun fact, I didn't have a 'shell' key in either Directory or Directory\Background in HKCU, so the script kept failing until I realized why, and manually created them. You may want to add some logic to check for both of those keys prior to attempting to create the "WindowsTerminal" key under them.

**Comment by kerol2r20** [comment]
Could you offer me the error output screenshot?

Thanks~

**Comment by chetgurevitch** [comment]
Here's the full program output. 
![image](https://user-images.githubusercontent.com/25513187/76110643-b6cde700-5f93-11ea-8e4c-7894057affdf.png)

After creating `HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell` and `HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell` everything runs fine.

**Comment by kerol2r20** [comment]
I have updated a new version to deal with this error.
You could try it!

Thanks

**Comment by kerol2r20** [comment]
If there is no any concern. I close this issue.

Thank you for your response!
