### ISSUE TITLE
Doesn't Read Profile List for Old Config Format

### ISSUE THREAD

**Issue by chetgurevitch** [kerol2r20/Windows-terminal-context-menu#9]
User configs generated before https://github.com/microsoft/terminal/pull/4556 store their profile list under .profiles rather than .profiles.list. There should probably be a disclaimer in the readme if not a check in the program to handle this on the fly.

@Kalaschnik this is what caused the error you got, you can get around it by either deleting and regenerating your user config or editing the script to source .profiles instead of .profiles.list

**Comment by kerol2r20** [comment]
Good information. Thanks~
